CMakeLists.txt
Without this flag, the debug build will run into errors when executables are run (because numopt and cpputil are (normally) installed with the march=native flags)
=> added march=native to the debug flags

include/AP1roG/AP1roGGeminalCoefficients.hpp, src/AP1roG/AP1roGGeminalCoefficients.cpp, tests/AP1roG/AP1roGPSESolver_test.cpp
This PR implements the ability to use the weak interaction limit for the AP1roG geminal coefficients as the initial guess for solving the PSEs.
=> Initial geminal coefficients in the weak interaction limit

drivers/hubbard.cpp
=> replaced incorrect constructor call in hubbard driver

include/FockSpace/FockPermutator.hpp
added missing reference indicator for the self-cast in the FockPermutator
=> CRTP-reference-cast

include/RHF/DIISRHFSCFSolver.hpp, src/RHF/DIISRHFSCFSolver.cpp
I did a force push to reset the changes that had been made, as I think updating the DIIS algorithm doesn't have to include the conditioning number step, since that seems to have no impact whatsoever.
The DIIS algorithm will be more flexible if we
- keep the `maximum_subspace_dimension`, such that if there are too many Fock matrices, the oldest one is discarded 
- introduce a `minimum_subspace_dimension`, such that DIIS is only enabled when there have been at least this many iterations (and thus Fock matrices)
=> Make the DIIS algorithm more flexible

.travis.yml, CMakeLists.txt, cmake/FindMKL.cmake
This PR fixes the Travis issues. In light of:
- the dependency on libcint and its dependency on a BLAS library
- the Eigen support for MKL and its current use in production
MKL is now required to compile GQCP (the -DEIGEN_USE_MKL has been deleted).
=> Point Travis to new libcint branch. MKL is now a hard requirement.

.travis.yml, benchmarks/CMakeLists.txt
This PR removes the dependency on the benchmark fork from tmhuysen.
=> Switch to conda installer for benchmark (Closes #319).

cmake/version.hpp.in, gqcpy/CMakeLists.txt, gqcpy/__init__.py.in, gqcpy/bindings.cpp, gqcpy/version.cpp
In this PR, I've implemented the printing of the version info upon loading `gqcpy`.
=> Add Python version info (closes #346)

.travis.yml
@tmhuysen has reported that currently the Travis build is broken due to a cache purge. As this should not influence any build procedures, this PR aims to resolve this bug.
=> Fix broken Travis installation.

CMakeLists.txt, README.md, drivers/CMakeLists.txt, tests/CMakeLists.txt
This PR is a follow-up for PR #368 and is intended to be able to use Boost versions higher than 1.69 (in order not to have a hard dependency on a specific version of Boost).
=> Refactor Boost support.

CMakeLists.txt, README.md, cmake/gqcp-config.cmake.in
This PR makes sure that headers are installed in `${INSTALL_PREFIX_PATH}/include/gqcp`. Hence, in accordance with the Eigen and Boost conventions, includes should have the form `#include "gqcp/gqcp.hpp".
=> Add additional layer in headers (resolves #292).

.travis.yml, CMakeLists.txt, README.md, include/Basis/Integrals/BaseOneElectronIntegralBuffer.hpp, include/Basis/Integrals/BaseOneElectronIntegralEngine.hpp, include/Basis/Integrals/BaseTwoElectronIntegralBuffer.hpp, include/Basis/Integrals/BaseTwoElectronIntegralEngine.hpp, include/Basis/Integrals/IntegralCalculator.hpp, include/Basis/Integrals/Interfaces/LibcintInterfacer.hpp, include/Basis/Integrals/Interfaces/LibcintOneElectronIntegralBuffer.hpp, include/Basis/Integrals/Interfaces/LibcintOneElectronIntegralEngine.hpp, include/Basis/Integrals/Interfaces/LibcintTwoElectronIntegralBuffer.hpp, include/Basis/Integrals/Interfaces/LibcintTwoElectronIntegralEngine.hpp, include/Basis/Integrals/Interfaces/LibintOneElectronIntegralBuffer.hpp, include/Basis/Integrals/Interfaces/LibintTwoElectronIntegralBuffer.hpp, src/Basis/LibcintInterfacer.cpp, tests/Basis/AOBasis_test.cpp, tests/HamiltonianParameters/HamiltonianParameters_test.cpp
Travis currently fails: this PR aims to resolve this.
**Longer description**
The error that Travis reported lead us to a bug that was introduced in #353. As it was related to some integrals being zero in the Libint2 calculations, I implemented a 'screening' function for the Libint buffers, which is a function that checks if all the integrals calculated over two or four shells are zero. Since the extension for the Libcint buffers and the implementation of the two-electron optimizers were straightforward (and my memory of Libcint was still fresh), this PR also closes #399.
=> Fix Travis

.github/workflows/gqcp.yml
Github action "Slack Notification" scripts depend on repository [secrets](https://help.github.com/en/actions/automating-your-workflow-with-github-actions/creating-and-using-encrypted-secrets). This appears to cause issues as forked repo's cannot retrieve the values from these secrets, for now the plan is to disable the notifications.
#464
=> URL for Slack notifications

gqcpy/src/Operator/SecondQuantized/SQHamiltonian.cpp, gqcpy/src/Operator/SecondQuantized/SQOneElectronOperator.cpp, gqcpy/src/QCMethod/HF/RHFSCFSolver.cpp
In this PR, I have implemented some convenient Python bindings for the addition of one-electron operators to a Hamiltonian.
=> Implement some convenient Python bindings

INSTALL.md, environment.yml
This PR updates the installation instructions with additional guidelines on how to link to PyBind11.
The underlying problem is marked as wontfix by PyBind11 https://github.com/pybind/pybind11/issues/99.
=> Update CMake flags for PyBind11 linking.

.github/workflows/build_website.yml, .github/workflows/deploy_website.yml
In this PR, I have made a distinction between a `push` to `develop` and a `pull_request`. The first will deploy the website to [the remote documentation site](https://gqcg.github.io/GQCP/) while the latter will only build it remotely to check if there are no compilation errors.
#609
=> Separate workflows for build and deploy website.

.github/workflows/conda.yml
This PR reenables support for CD MacOS Conda GQCP packages.
This PR is a replacement for PR #644. PR #644 shows that this PR should not fail when pushed to develop.
=> Enable MacOS Conda package build (closes #597).

gqcp/include/Processing/DensityMatrices/OneDM.hpp, gqcp/include/QCModel/CI/LinearExpansion.hpp, gqcpy/gqcpy.cpp, gqcpy/src/Processing/CMakeLists.txt, gqcpy/src/Processing/DensityMatrices/CMakeLists.txt, gqcpy/src/Processing/DensityMatrices/OneDM_bindings.cpp, gqcpy/src/Processing/DensityMatrices/SpinResolvedOneDM_bindings.cpp, gqcpy/src/Processing/DensityMatrices/SpinResolvedTwoDM_bindings.cpp, gqcpy/src/Processing/DensityMatrices/TwoDM_bindings.cpp, gqcpy/src/QCMethod/HF/UHF/UHFSCFEnvironment_bindings.cpp, gqcpy/src/QCModel/CI/LinearExpansion_bindings.cpp
The functionality to work with both spin resolved and regular density matrix types in python will prove to be very valuable further down the road. In this PR I will tackle this functionality.
- closes #677 
I have removed the `spinDensity` binding from `linearExpansion`, since the `SpinResolvedOneDM` binding can now calculate this for us. I have, however, added the `calculateSpinResolved1DM` and `calculateSpinResolved2DM` functionalities to the `linearExpansion` bindings. This grants a lot of freedom to manipulate the density matrices using the python bindings. 
=> Density matrix bindings

gqcp/include/Mathematical/Functions/LinearCombination.hpp, gqcp/include/Mathematical/Functions/VectorSpaceArithmetic.hpp, gqcp/include/Operator/SecondQuantized/SimpleSQOneElectronOperator.hpp, gqcp/include/QCModel/CC/T1Amplitudes.hpp, gqcp/include/QCModel/CC/T2Amplitudes.hpp, gqcp/tests/Operator/SecondQuantized/SQOneElectronOperator_test.cpp
In line with the large operator refactor going on right now, I'll use this PR to tackle some smaller issues that are related to vector space arithmetic.
- closes #415 
Issue #415 has different parts to it:
=> Vector space arithmetic

gqcp/tests/Mathematical/Representation/CMakeLists.txt, gqcp/tests/Mathematical/Representation/DenseVectorizer_test.cpp
The Dense vectoriser class did not have any unit testing yet. This PR adds the necessary tests.
closes #691 
The `offset` method now has a test for both `RowMajor` and `ColumnMajor` in case of a 2D array/matrix. I've also added a test for a 3D array/matrix.
=> DenseVectorizer test

gqcp/include/Basis/SpinorBasis/GSpinorBasis.hpp, gqcp/include/Basis/SpinorBasis/RSpinOrbitalBasis.hpp, gqcp/include/DensityMatrix/G1DM.hpp, gqcp/include/DensityMatrix/G2DM.hpp, gqcp/include/DensityMatrix/Orbital1DM.hpp, gqcp/include/DensityMatrix/SpinDensity1DM.hpp, gqcp/include/DensityMatrix/SpinResolved1DMComponent.hpp, gqcp/include/DensityMatrix/SpinResolved2DMComponent.hpp, gqcp/include/Operator/SecondQuantized/EvaluatableScalarRSQOneElectronOperator.hpp, gqcp/include/Operator/SecondQuantized/SQOperatorStorageBase.hpp
In the current code, a trait is alternatively defined as a `struct` or `class`. In my opinion, it would be better to implement them all as `struct`s as their members should be stored as `public`.
Closes #706.
=> PR: Change class to struct for traits.

gqcp/tests/Processing/Properties/CMakeLists.txt, gqcp/tests/Processing/Properties/properties_test.cpp
This PR cleans up `properties_test.cpp`. It also closes #751. (This issue should already have been closed, since the Dyson amplitude calculation was already re-enabled).
=> Clean up test.

gqcp/include/ONVBasis/ONVPath.hpp, gqcp/include/ONVBasis/SpinResolvedONVBasis.hpp, gqcp/include/QCModel/CI/LinearExpansion.hpp, gqcp/tests/QCModel/CI/CMakeLists.txt, gqcp/tests/QCModel/CI/LinearExpansion_test.cpp
@dariatols The previous implementation from #705 was very wrong. You were emplacing elements in an ONV-basis-dimensional object. I've tried to improve upon the algorithm, but without any success yet. The reason your tests weren't picking up any errors was just plain-old luck in my opinion. Feel free to adjust any estimates according to your thoughts.
=> Implement 1-DM for linear expansions in spin-unresolved ONV bases

gqcp/include/QCModel/HF/GHF.hpp, gqcp/include/QCModel/HF/RHF.hpp, gqcp/include/QCModel/HF/StabilityMatrices/CMakeLists.txt, gqcp/include/QCModel/HF/StabilityMatrices/GHFStabilityMatrices.hpp, gqcp/include/QCModel/HF/StabilityMatrices/RHFStabilityMatrices.hpp, gqcp/include/gqcp.hpp, gqcp/tests/QCMethod/HF/GHF/QCMethod_GHF_stability_test.cpp, gqcp/tests/QCMethod/HF/RHF/CMakeLists.txt, gqcp/tests/QCMethod/HF/RHF/QCMethod_RHF_stability_test.cpp
This is the second PR that tackles the Hartree-Fock Stability checks. In this one, the restricted Hartree-Fock stability conditions are implemented. 
- closes #788 
As well as implementing the RHF stability conditions, this PR fixes some minor mistakes in the GHF stability analysis I encountered along the way.
=> RHF Stability analysis

gqcp/include/QCModel/HF/GHF.hpp, gqcp/include/QCModel/HF/RHF.hpp
I renamed the API to show that it calculates all possible excitation energies and updated the documentation accordingly.
=> Rename the FockOperatorEigenvalue API

gqcp/include/Operator/SecondQuantized/SQHamiltonian.hpp, gqcp/include/QCModel/CI/LinearExpansion.hpp, gqcpy/include/interfaces.hpp, gqcpy/src/Operator/SecondQuantized/SQHamiltonian_bindings.cpp, gqcpy/src/Operator/SecondQuantized/USQOneElectronOperator_bindings.cpp, gqcpy/src/QCModel/CI/LinearExpansion_bindings.cpp
=> Implement Python bindings for spin-redistributions on Hubbard.

CMakeLists.txt, cmake/version.hpp.in, gqcp/CMakeLists.txt
I have provided some small corrections regarding the version of `GQCP`. See chapter 19 in [Professional CMake](https://crascit.com/professional-cmake/) for extra reading material on common practices regarding version details in projects.
Link to the open (and possibly closed) issues that are related to this pull request. If this pull request fully closes an issue, please use GitHub's closing keywords. 
**To do**
=> [CMake] GQCP version refactor

CMakeLists.txt, gqcp/CMakeLists.txt
It is a recommended practice to set the header search path during `install()` rather than using the `$<INSTALL_INTERFACE:...>` generator expression on the `gqcp_version` target itself. I have removed the redundant install generator expression in `gqcp` as well, since this header path file was already accounted for in the ìnstall()` command.
**To do**
=> [CMake] Small adjustment for installation ofgqcp and  gqcp_version.

CMakeLists.txt, cmake/version.cpp.in, cmake/version.hpp.in, gqcpy/__init__.py.in, gqcpy/version.cpp
Add gqcp_version with compiled source file instead of header file. This way, `gqcp` (and `gqcpy`) does not need to be recompiled if the version should be modified.
**To do**
=> [CMake] Refactor gqcp_version to a static library instead of header-only.

gqcp/include/Basis/Integrals/CMakeLists.txt, gqcp/include/Basis/Integrals/FunctionalPrimitiveEngine.hpp, gqcp/include/Basis/Integrals/McMurchieDavidsonCoefficient.hpp, gqcp/include/gqcp.hpp, gqcp/src/Basis/Integrals/McMurchieDavidsonCoefficient.cpp, gqcpy/gqcpy.cpp, gqcpy/src/Basis/CMakeLists.txt, gqcpy/src/Basis/Integrals/CMakeLists.txt, gqcpy/src/Basis/Integrals/FunctionalPrimitiveEngine_bindings.cpp, gqcpy/src/Basis/Integrals/IntegralCalculator_bindings.cpp, gqcpy/src/Basis/Integrals/McMurchieDavidsonCoefficient_bindings.cpp, gqcpy/src/Basis/Integrals/OneElectronIntegralEngine_bindings.cpp, gqcpy/src/Basis/ScalarBasis/CMakeLists.txt, gqcpy/src/Basis/ScalarBasis/ScalarBasis_bindings.cpp, gqcpy/src/Basis/ScalarBasis/ShellSet_bindings.cpp, gqcpy/src/Basis/SpinorBasis/RSpinOrbitalBasis_bindings.cpp, gqcpy/src/Mathematical/CMakeLists.txt, gqcpy/src/Mathematical/Functions/CMakeLists.txt, gqcpy/src/Mathematical/Functions/CartesianDirection_bindings.cpp, gqcpy/src/Mathematical/Functions/CartesianExponents_bindings.cpp, gqcpy/src/Mathematical/Functions/CartesianGTO_bindings.cpp, website/examples/Calculating integrals over GTOs.ipynb
In this PR, I'll make sure to open up the Python bindings so we can add a Jupyter Notebook tutorial on our website that enables users to implement their own 'primitive' (non-Coulomb) engines in order to calculate the corresponding integrals. 
Closes #906.
**To do**
=> Provide tutorial on calculating GTO overlap integrals

.github/workflows/build-and-test.yml, cmake/gqcp-config.cmake.in
In this PR I aim to get rid of the requirement that `CMAKE_MODULE_PATH` has to be set manually through command line options passed to CMake.
=> Refactor CMake such that CMAKE_MODULE_PATH no longer has to be set.

gqcpy/include/interfaces.hpp, gqcpy/src/DensityMatrix/MixedSpinResolved2DMComponent_bindings.cpp
This small bug fix solves the issue where we couldn't use the `.tensor()` API in the python bindings to acces 2DMs and their components.
closes #940 
**To do**
=> fix tensor bindings for 2DM's

gqcpy/src/ONVBasis/SpinResolvedONVBasis_bindings.cpp, gqcpy/src/ONVBasis/SpinUnresolvedONVBasis_bindings.cpp
The `forEach` method does not work without automatic conversion from `pybind`'s `functional.h` header. This PR adds the automatic conversion of Python functions to C++ `std::function`s in `SpinResolved`- and `SpinUnresolvedONVBasis` objects.
**To do**
=> Add functional header for ONVBasis bindings.

gqcpy/src/Operator/SecondQuantized/EvaluableRSQOneElectronOperator_bindings.cpp
This PR fixes the Python bindings for evaluating current density matrix elements.
**To do**
=> Fix evaluate bindings.

.github/workflows/ci-cd-conda.yml, CMakeLists.txt, conda/meta.yaml, tools/HEADER, tools/conda.recipe/meta.yaml
Anaconda tokens have an expiration date and the Anaconda Client does **not** warn when this token has expired, nor does it notify that the upload has failed. I have updated the token and I am now testing if uploading again works. Update: updating the token indeed fixes the upload.
=> Fix GA conda uploads to Anaconda. Closes #967.
