GQCG/GQCP

- cmake/SetCMakeEnvironment.cmake
- src/RHF/DIISRHFSCFSolver.cpp
- src/RHF/PlainRHFSCFSolver.cpp
- src/RHF/RHF.cpp
- src/RHF/RHFSCFSolver.cpp
> fixed cmake

- cmake/SetCMakeEnvironment.cmake
- include/FockSpace/FockSpaceType.hpp
- include/FockSpace/ProductFockSpace.hpp
- include/FockSpace/SelectedFockSpace.hpp
- include/HamiltonianBuilder/FCI.hpp
- include/RDM/FCIRDMBuilder.hpp
- include/RDM/RDMCalculator.hpp
- src/FockSpace/ProductFockSpace.cpp
- src/FockSpace/SelectedFockSpace.cpp
- src/HamiltonianBuilder/FCI.cpp
- src/RDM/FCIRDMBuilder.cpp
- src/RDM/RDMCalculator.cpp
- tests/CISolver/CISolver_FCI_Davidson_test.cpp
- tests/CISolver/CISolver_FCI_Dense_test.cpp
- tests/FockSpace/ProductFockSpace_test.cpp
- tests/FockSpace/SelectedFockSpace_test.cpp
- tests/HamiltonianBuilder/FCI_test.cpp
- tests/OO_DOCI_test.cpp
- tests/RDM/FCIRDMBuilder_test.cpp
- tests/RDM/RDMCalculator_test.cpp
- tests/RDM/SelectedRDMBuilder_test.cpp
> Rename to ProductFockSpace

- CMakeLists.txt
- cmake/FindPackages.cmake
- cmake/SetCMakeEnvironment.cmake
- exe/CMakeLists.txt
- exe/fci_lowdin.cpp
- exe/oo_doci_rhf.cpp
- include/HamiltonianParameters/HamiltonianParameters.hpp
- src/HamiltonianParameters/HamiltonianParameters.cpp
> Executables for current projects

- src/AP1roG/AP1roGJacobiOrbitalOptimizer.cpp
- src/AP1roG/AP1roGPSESolver.cpp
- src/DOCINewtonOrbitalOptimizer.cpp
In numopt, I removed a typedef instead of 'deprecating' it, so here are the downstream changes.
> Fix API changes from numopt.

- .gitignore
- cmake/ConfigureExecutable.cmake
- cmake/ConfigureLibrary.cmake
- cmake/FindMKL.cmake
- cmake/FindPackages.cmake
- src/RHF/RHFSCFSolver.cpp
This could be part of the solution to GQCG/gqcp#109.
> CMake update include and libs.

- .travis.yml
Faster compilations should lead to shorter development iterations. This commit enables make to run in parallel.
> Try to speed up Travis compilation.

- include/FockSpace/FockSpace.hpp
- include/FockSpace/ONV.hpp
- src/FockSpace/FockSpace.cpp
- src/FockSpace/ONV.cpp
- src/FockSpace/SelectedFockSpace.cpp
- src/HamiltonianBuilder/Hubbard.cpp
> can now set an ONV to a desired address

- include/FockSpace/FockSpace.hpp
- src/FockSpace/FockSpace.cpp
- src/HamiltonianBuilder/DOCI.cpp
- tests/FockSpace/FockSpace_test.cpp
> updated fock space function and DOCI algorithm to remove overhead

- .travis.yml
- CMakeLists.txt
- cmake/FindLibint2.cmake
- cmake/FindPackages.cmake
In this issue, I will resolve all current cluster compilation problems.
> Bug fix: cluster compilation.

- cmake/InstallLibrary.cmake
> Copy directory structure includes.

- cmake/Definitions/Tests.cmake
- src/FockSpace/FockSpace.cpp
- src/FockSpace/ProductFockSpace.cpp
- tests/FockSpace/FockSpace_test.cpp
- tests/FockSpace/ProductFockSpace_test.cpp
> master - hotfix/error_rdm_patch

- include/DOCINewtonOrbitalOptimizer.hpp
This PR includes some small changes that are needed to implement other drivers.
> Extra changes for drivers

- .travis.yml
- CMakeLists.txt
- cmake/Configure/ConfigureLibrary.cmake
- cmake/Definitions/CMakeDefinitions.cmake
- cmake/Find/FindLibcint.cmake
- cmake/Find/FindLibint2.cmake
- cmake/Find/FindSpectra.cmake
This pull request will make the CMake build more modern, adhering to the philosophy of targets and properties (https://pabloariasal.github.io/2018/02/19/its-time-to-do-cmake-right/).
> CMake update: targets and properties.

- tests/units_test.cpp
This resolves error with compilation on the cluster
> Added header to comply with intel compiler (Closes #285)

- gqcpy/QCMethod/FCI.cpp
- gqcpy/QCMethod/Hubbard.cpp
This PR will add documentation on the currently implemented Python bindings.
> Add Python documentation

- include/Properties/properties.hpp
- src/Properties/properties.cpp
- tests/Properties/properties_test.cpp
Contains a function to calculate the coefficients of a Dyson orbital between two wave functions differing a single electron and which are expressed in the same basis. 
Partially resolves issue #422
**Additional info**
**To-Do**
Q: Should we have reference data before proceeding? How can we test if the code is correct?
**Follow-up**
A follow up PR will contain a pybinding for quick use
> Dyson orbital coefficients

- cmake/Doxyfile.in
This bugfix adds subdirectories that contain classes to the Doxyfile.
> Bugfix: add classes in subdirectories to Doxygen documentation.

- include/Mathematical/Representation/BlockMatrix.hpp
- include/Mathematical/Representation/BlockRankFourTensor.hpp
- include/Operator/SecondQuantized/SQHamiltonian.hpp
- include/Properties/BaseElectricalResponseSolver.hpp
- include/Properties/CMakeLists.txt
- include/Properties/RHFElectricalResponseSolver.hpp
- include/Properties/properties.hpp
- include/RHF/RHF.hpp
- include/gqcp.hpp
- src/Properties/BaseElectricalResponseSolver.cpp
- src/Properties/CMakeLists.txt
- src/Properties/RHFElectricalResponseSolver.cpp
- src/Properties/properties.cpp
- src/RHF/RHF.cpp
- tests/Properties/properties_test.cpp
In this PR, I will implement CPHF for electrical response properties.
This PR:
*None*
> Implement CPHF for electrical properties

- include/Basis/SingleParticleBasis.hpp
- include/Basis/transform.hpp
- include/Operator/SecondQuantized/CMakeLists.txt
- include/Operator/SecondQuantized/SQHamiltonian.hpp
- include/Operator/SecondQuantized/USQHamiltonian.hpp
- include/gqcp.hpp
- tests/Operator/SecondQuantized/CMakeLists.txt
- tests/Operator/SecondQuantized/USQHamiltonian_test.cpp
This PR implements:
GQCG/constrained_outline#4
Beginnings for an unrestricted framework. 
> added the USQHamiltonian

- .github/workflows/gqcp.yml
Perform continuous integration using Github actions
> CI: Github actions

- .github/workflows/gqcp.yml
Make it so the github actions actually run the test
#471
> Fix test runs for github actions

- .github/workflows/gqcp.yml
This PR is aimed at resolving the current Github Actions failures.
> Bugfix: Github Actions.

- gqcp/include/Basis/SpinorBasis/GSpinorBasis.hpp
- gqcp/tests/Basis/SpinorBasis/GSpinorBasis_test.cpp
This PR fixes #519. (@xdvriend)
> Bugfix: quantization of the Coulomb operator in a general spinor basis

- gqcp/include/Operator/SecondQuantized/SQHamiltonian.hpp
- gqcpy/src/Operator/SecondQuantized/SQHamiltonian.cpp
- gqcpy/src/Operator/SecondQuantized/SQOneElectronOperator.cpp
- gqcpy/src/Operator/SecondQuantized/SQTwoElectronOperator.cpp
This PR closes #544. (@xdvriend)
> Implement python bindings for SQOperator transformations.

- gqcpy/gqcpy.cpp
- gqcpy/src/ONVBasis/CMakeLists.txt
- gqcpy/src/ONVBasis/SeniorityZeroONVBasis.cpp
- gqcpy/src/QCMethod/CI/CIEnvironment.cpp
This PR implements the required Python bindings in order to do DOCI calculations.
> DOCI bindings

- gqcp/include/Operator/SecondQuantized/CMakeLists.txt
- gqcp/include/Operator/SecondQuantized/USQOneElectronOperator.hpp
- gqcp/include/Utilities/typedefs.hpp
- gqcp/tests/Operator/SecondQuantized/CMakeLists.txt
- gqcp/tests/Operator/SecondQuantized/SQOneElectronOperator_test.cpp
- gqcp/tests/Operator/SecondQuantized/USQOneElectronOperator_test.cpp
Adding the Unrestricted Second Quantized operators, in order to later perform unrestricted calculations.
This PR aims to solve the first part of #558 
Trying to follow the structure of the restricted SQOperators as much as possible.
> USQOneElectronOperator

- INSTALL.md
- environment.yml
This PR will ensure that developers can install GQCP locally and on the HPC clusters.
> Devops: get gqcp_dev local and on HPC clusters

- gqcp/include/Molecule/Molecule.hpp
- gqcp/include/Molecule/NuclearFramework.hpp
- gqcp/src/Molecule/Molecule.cpp
- gqcp/src/Molecule/NuclearFramework.cpp
- gqcp/tests/Molecule/NuclearFramework_test.cpp
- gqcpy/src/Molecule/Molecule.cpp
A small PR containing a few extras I have implemented during the calculations on an H3-ring.
This PR:
- closes #537;
- closes #431.
> Implementations for H3

- gqcp/include/ONVBasis/SeniorityZeroONVBasis.hpp
- gqcp/include/Processing/Properties/BaseElectricalResponseSolver.hpp
- gqcp/include/Processing/Properties/CIElectricalResponseSolver.hpp
- gqcp/include/Processing/Properties/CMakeLists.txt
- gqcp/include/Processing/Properties/properties.hpp
- gqcp/include/Processing/Properties/vAP1roGElectricalResponseSolver.hpp
- gqcp/include/QCModel/CI/LinearExpansion.hpp
- gqcp/include/QCModel/Geminals/AP1roG.hpp
- gqcp/include/QCModel/Geminals/AP1roGGeminalCoefficients.hpp
- gqcp/include/QCModel/Geminals/vAP1roG.hpp
- gqcp/src/ONVBasis/SeniorityZeroONVBasis.cpp
- gqcp/src/Processing/Properties/CMakeLists.txt
- gqcp/src/Processing/Properties/properties.cpp
- gqcp/src/Processing/Properties/vAP1roGElectricalResponseSolver.cpp
- gqcpy/gqcpy.cpp
- gqcpy/src/CMakeLists.txt
- gqcpy/src/Operator/FirstQuantized/Operator.cpp
- gqcpy/src/Processing/CMakeLists.txt
- gqcpy/src/Processing/Properties/CMakeLists.txt
- gqcpy/src/Processing/Properties/RHFElectricalResponseSolver.cpp
- gqcpy/src/QCMethod/CI/DOCINewtonOrbitalOptimizer.cpp
- gqcpy/src/QCModel/CI/LinearExpansion.cpp
- gqcpy/src/QCModel/Geminals/vAP1roG.cpp
In this PR, I'll implement changes as I need them for writing the geminals response paper.
This PR:
- closes #325;
- closes #328.
> Implementations for geminals response

- cmake/Doxyfile.in
- gqcp/include/Mathematical/CMakeLists.txt
- gqcp/include/Mathematical/Grid/CMakeLists.txt
- gqcp/include/Mathematical/Grid/CubicGrid.hpp
- gqcp/include/Mathematical/Grid/Field.hpp
- gqcp/include/gqcp.hpp
- gqcp/src/Mathematical/CMakeLists.txt
- gqcp/src/Mathematical/Grid/CMakeLists.txt
- gqcp/src/Mathematical/Grid/CubicGrid.cpp
- gqcp/tests/Mathematical/CMakeLists.txt
- gqcp/tests/Mathematical/Grid/CMakeLists.txt
- gqcp/tests/Mathematical/Grid/Field_test.cpp
In this PR, I will provide some basic grid-related types, related to some old code we had written.
This PR:
> Implement basic grid-related types.

- .travis.yml
- gqcp/include/Basis/Integrals/BaseOneElectronIntegralBuffer.hpp
- gqcp/include/Basis/ScalarBasis/ShellSet.hpp
- gqcp/include/Mathematical/Grid/CubicGrid.hpp
- gqcp/include/Mathematical/Grid/Field.hpp
- gqcp/include/ONVBasis/SeniorityZeroONVBasis.hpp
- gqcp/include/ONVBasis/SpinUnresolvedONV.hpp
- gqcp/src/Mathematical/Grid/CubicGrid.cpp
- gqcp/src/ONVBasis/SeniorityZeroONVBasis.cpp
- gqcp/src/ONVBasis/SpinUnresolvedONV.cpp
- gqcp/src/Operator/FirstQuantized/Operator.cpp
- gqcp/tests/Basis/ScalarBasis/CMakeLists.txt
- gqcp/tests/Basis/ScalarBasis/GTOBasisSet_test.cpp
- gqcp/tests/Basis/ScalarBasis/ShellSet_test.cpp
- gqcp/tests/Mathematical/Grid/Field_test.cpp
- gqcp/tests/ONVBasis/CMakeLists.txt
- gqcp/tests/ONVBasis/SeniorityZeroONVBasis_test.cpp
- gqcp/tests/Processing/Properties/expectation_values_test.cpp
In this PR, I will fix recently introduced `std::vector` bugs.
> Fix std::vector bugs

- gqcp/include/Operator/SecondQuantized/SQOneElectronOperator.hpp
- gqcp/tests/Operator/SecondQuantized/SQOneElectronOperator_test.cpp
This is a small PR that performs some small maintenance:
- closes #562.
> General maintenance

- .travis.yml
> Bugfix: Travis Python support (closes #602)

- gqcp/include/Molecule/Molecule.hpp
- gqcp/include/Molecule/NuclearFramework.hpp
- gqcp/include/Molecule/Nucleus.hpp
- gqcp/src/Molecule/Molecule.cpp
- gqcp/src/Molecule/NuclearFramework.cpp
- gqcp/src/Molecule/Nucleus.cpp
- gqcp/tests/Molecule/Molecule_test.cpp
- gqcpy/src/Molecule/Molecule_bindings.cpp
A small PR to address issue #610 
#610 
> Refactor molecule printing

- site/docs/developer_documentation/getting_started.md
- site/docs/developer_documentation/introduction.md
A branch that gathers documentation improvements.
#607
> Improve documentation

- .github/workflows/build_website.yml
- .github/workflows/deploy_website.yml
- .github/workflows/test_benchmarks.yml
- site/docs/documentation.md
> Update website GitHub Actions

- gqcp/include/Molecule/Nucleus.hpp
A missing header was found in one of the files.
Added the needed header.
> Bugfix: missing header

- .github/workflows/docker-gqcp-build.yml
- CMakeLists.txt
- conda/build.sh
- conda/conda_build_config.yaml
- conda/meta.yaml
- gqcp/CMakeLists.txt
- gqcp/include/Basis/Integrals/BaseOneElectronIntegralBuffer.hpp
This PR will provide a framework for releases, where Conda/Docker images are built on pull_request and deployed on merge.
> Update GA for release (closes #666, closes #670).

- gqcp/include/Operator/SecondQuantized/USQHamiltonian.hpp
- gqcp/include/QCModel/CI/LinearExpansion.hpp
- gqcpy/gqcpy.cpp
- gqcpy/src/Basis/SpinorBasis/USpinorBasis_bindings.cpp
- gqcpy/src/Operator/SecondQuantized/CMakeLists.txt
- gqcpy/src/Operator/SecondQuantized/USQHamiltonian_bindings.cpp
- gqcpy/src/QCModel/CI/LinearExpansion_bindings.cpp
A clear and concise description of what is (to be) done in this PR.
Issue #663 
Working on the python bindings for USQ Hamiltonian in order to do unrestricted CI calculations.
> USQHamiltonian python bindings

- Dockerfile
- site/docs/user_documentation/getting_started.md
Adds info on how access Jupyter notebooks running in remote Singularity containers from your local browser.
> Jupyter and Singularity

- gqcp/include/Basis/SpinorBasis/SimpleSpinorBasis.hpp
> Fix method override.

- gqcp/include/Operator/SecondQuantized/USQTwoElectronOperator.hpp
> Bugfix override

- gqcp/include/Operator/SecondQuantized/SQHamiltonian.hpp
> Improve arithmetic operators on SQHamiltonian.

- gqcp/tests/QCMethod/CI/FCI_test.cpp
> Implement a natural orbital test. Closes #154.

- site/website/pages/en/index.js
I noticed that in the PR of @guacke, the only thing that wasn't done was adding the link to the actual button on the website.
This PR fixes that!
> Try out button now up and running!

- gqcp/include/Processing/Properties/DysonOrbital.hpp
- gqcp/tests/Processing/Properties/DysonOrbital_test.cpp
Closes https://github.com/GQCG/GQCP/issues/859.
> Dyson orbital for SpinUnresolved ONV basis

- gqcp/tests/Basis/Integrals/Interfaces/LibintInterfacer_test.cpp
- gqcp/tests/Basis/ScalarBasis/GTOBasisSet_test.cpp
- gqcp/tests/Basis/Transformations/JacobiRotation_test.cpp
- gqcp/tests/Basis/Transformations/OrbitalRotationGenerators_test.cpp
- gqcp/tests/Mathematical/Functions/CartesianExponents_test.cpp
- gqcp/tests/Mathematical/Optimization/Eigenproblem/Eigenpair_test.cpp
- gqcp/tests/Mathematical/Optimization/Eigenproblem/EigenproblemSolver_test.cpp
- gqcp/tests/Mathematical/Optimization/Minimization/IterativeIdentitiesHessianModifier_test.cpp
- gqcp/tests/Mathematical/Optimization/Minimization/Minimizer_test.cpp
- gqcp/tests/Mathematical/Optimization/NonLinearEquation/NonLinearEquationSolver_test.cpp
- gqcp/tests/Mathematical/Representation/Matrix_test.cpp
- gqcp/tests/Mathematical/Representation/SquareMatrix_test.cpp
- gqcp/tests/Mathematical/Representation/SquareRankFourTensor_test.cpp
- gqcp/tests/Mathematical/Representation/Tensor_test.cpp
- gqcp/tests/Molecule/Nucleus_test.cpp
- gqcp/tests/Molecule/elements_test.cpp
- gqcp/tests/ONVBasis/ONVPath_test.cpp
- gqcp/tests/ONVBasis/SpinResolvedONVBasis_test.cpp
- gqcp/tests/ONVBasis/SpinUnresolvedONVBasis_test.cpp
- gqcp/tests/ONVBasis/SpinUnresolvedONV_test.cpp
- gqcp/tests/Operator/FirstQuantized/NuclearDipoleOperator_test.cpp
- gqcp/tests/Operator/FirstQuantized/NuclearRepulsionOperator_test.cpp
- gqcp/tests/Operator/SecondQuantized/SQHamiltonian_test.cpp
- gqcp/tests/Processing/Properties/properties_test.cpp
- gqcp/tests/QCMethod/CI/DOCI_test.cpp
- gqcp/tests/QCMethod/CI/FCI_test.cpp
- gqcp/tests/QCMethod/RMP2/RMP2_test.cpp
- gqcp/tests/Utilities/miscellaneous_test.cpp
- gqcp/tests/Utilities/units_test.cpp
> Improvements to tests

- gqcpy/src/DensityMatrix/MixedSpinResolved2DMComponent_bindings.cpp
- gqcpy/src/DensityMatrix/PureSpinResolved2DMComponent_bindings.cpp
> Add numpy conversions for 2DM components.

- cmake/Doxyfile.in
- gqcp/include/Mathematical/Representation/SquareMatrix.hpp
- gqcp/include/Operator/SecondQuantized/ModelHamiltonian/AdjacencyMatrix.hpp
- gqcp/include/Operator/SecondQuantized/ModelHamiltonian/CMakeLists.txt
- gqcp/include/Operator/SecondQuantized/ModelHamiltonian/HoppingMatrix.hpp
- gqcp/include/Operator/SecondQuantized/ModelHamiltonian/HubbardHamiltonian.hpp
- gqcp/include/gqcp.hpp
- gqcp/src/ONVBasis/SpinResolvedONVBasis.cpp
- gqcp/src/Operator/CMakeLists.txt
- gqcp/src/Operator/SecondQuantized/CMakeLists.txt
- gqcp/src/Operator/SecondQuantized/ModelHamiltonian/AdjacencyMatrix.cpp
- gqcp/src/Operator/SecondQuantized/ModelHamiltonian/CMakeLists.txt
- gqcp/tests/Operator/SecondQuantized/CMakeLists.txt
- gqcp/tests/Operator/SecondQuantized/ModelHamiltonian/AdjacencyMatrix_test.cpp
- gqcp/tests/Operator/SecondQuantized/ModelHamiltonian/CMakeLists.txt
- gqcp/tests/Operator/SecondQuantized/ModelHamiltonian/HoppingMatrix_test.cpp
- gqcp/tests/QCMethod/CI/Hubbard_test.cpp
- gqcpy/gqcpy.cpp
- gqcpy/src/Operator/SecondQuantized/ModelHamiltonian/AdjacencyMatrix_bindings.cpp
- gqcpy/src/Operator/SecondQuantized/ModelHamiltonian/CMakeLists.txt
- gqcpy/src/Operator/SecondQuantized/ModelHamiltonian/HoppingMatrix_bindings.cpp
- gqcpy/src/Operator/SecondQuantized/ModelHamiltonian/HubbardHamiltonian_bindings.cpp
- website/examples/Hubbard.ipynb
I've improved the Hubbard APIs so they become more useful in a Python notebook.
#878
**To do**
> Improve Hubbard APIs

- gqcpy/src/ONVBasis/SpinResolvedONVBasis_bindings.cpp
- gqcpy/src/ONVBasis/SpinUnresolvedONVBasis_bindings.cpp
- gqcpy/src/ONVBasis/SpinUnresolvedONV_bindings.cpp
I have added some extra bindings that will come in handy in my notebook concerning the reproducibility of Hubbard MPDs and future research.
> Extra bindings for ONVBasis.

- gqcp/include/QCMethod/CC/CCD.hpp
- gqcp/include/QCMethod/CC/CCDEnergyCalculation.hpp
- gqcp/include/QCMethod/CC/CCDSolver.hpp
- gqcp/include/QCMethod/CC/CCSD.hpp
- gqcp/include/QCMethod/CC/CCSDEnergyCalculation.hpp
- gqcp/include/QCMethod/CC/CCSDEnvironment.hpp
- gqcp/include/QCMethod/CC/CMakeLists.txt
- gqcp/include/QCMethod/CC/T2DIIS.hpp
- gqcp/include/QCMethod/CC/T2ErrorCalculation.hpp
- gqcp/include/QCModel/CC/T1Amplitudes.hpp
- gqcp/include/QCModel/CC/T2Amplitudes.hpp
- gqcp/include/gqcp.hpp
- gqcp/tests/QCMethod/CC/QCMethod_CCD_test.cpp
- gqcp/tests/QCMethod/CC/QCMethod_CCSD_test.cpp
- gqcpy/src/Basis/SpinorBasis/GSpinorBasis_bindings.cpp
- gqcpy/src/QCMethod/CC/CCDSolver_bindings.cpp
- gqcpy/src/QCMethod/CC/CCSDEnvironment_bindings.cpp
- gqcpy/src/QCModel/CC/T1Amplitudes_bindings.cpp
- gqcpy/src/QCModel/CC/T2Amplitudes_bindings.cpp
- website/examples/CCSD.ipynb
In this PR, I've updated some CC-related types, and I've implemented a first try for CC DIIS. I'm still experimenting with the implementation, but I'd like to merge some work to develop already, so I can rebuild production containers.
**To do**
> CC-related improvements

- CMakeLists.txt
- gqcpy/tests/test_version.py
> Bugfix: gqcpy does not show git SHA.

- gqcp/include/ONVBasis/SpinResolvedONVBasis.hpp
- gqcpy/src/ONVBasis/SpinResolvedONVBasis_bindings.cpp
- gqcpy/src/ONVBasis/SpinUnresolvedONVBasis_bindings.cpp
I have adjusted and added some extra bindings regarding `ONV` representations.
**To do**
> Extra bindings for ONVBasis objects.

- gqcpy/src/Basis/SpinorBasis/GSpinorBasis_bindings.cpp
> Add ability to quantize magnetic Hamiltonian in GSpinorBasis
